// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xigituxddrtsqhmrmsvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpZ2l0dXhkZHJ0c3FobXJtc3Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NTcwMDAsImV4cCI6MjA4ODIzMzAwMH0.8KXeDbspZytrCxBdZcgMraBtlicfcYhN4XmwRNZgqNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});